# Generated by Django 4.2.27 on 2026-02-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotater', '0002_alter_retailrow_id'),
        ('annotater', '0002_alter_retailrow_id 2'),
    ]

    operations = [
    ]
