# Generated by Django 4.2.27 on 2026-02-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotater', '0003_merge_20260204_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailrow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
