# Generated by Django 4.2.27 on 2026-02-06 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotater", "0004_alter_retailrow_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailrow",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="retailrow",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="retailrow",
            name="country",
            field=models.CharField(max_length=3),
        ),
    ]
