# Generated by Django 4.2.27 on 2026-02-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotater", "0005_retailrow_created_at_retailrow_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailrow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="retailrow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
